### ISSUE TITLE
Unable to resolve module 'asyncstorage-down' from 'node_modules/react-native-level-fs/index.js'

### ISSUE THREAD

**Issue by karriz-dev** [jimni1222/testCRNA#13]
```shell
npm install
react-native run-android 
```
해당 프로젝트를 클론하여 위 두 명령어를 실행 했을 때 오류가 발생했습니다.

> Unable to resolve module 'asyncstorage-down' from 'node_modules/react-native-level-fs/index.js'

혹시 업데이트 된 내용이 있는지 공유바랍니다.

또한 제가 별도 프로젝트 작업을 해서 실행 했을 때 
> Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference

위 에러가 발생했는데 제가 확인 할 수 있는 부분이 있을까요 ?

**Comment by jimni1222** [comment]
이 리포는 오랜 기간동안 유지보수 되지 않았습니다.
최신 create react native app을 사용하셔서 프로젝트를 구성하시기 바랍니다.

**Comment by karriz-dev** [comment]
추가 해결 내용 전달합니다.

위 asyncstorage-down 오류가 발생한다면, 아래 명령어를 입력하여 수정해보세요.

```
npm i asyncstorage-down
npm run postinstall
react-native run-android
```
